import { toggleMenu } from "./toggleMenu.js";
import { registerValidation } from "./registration.js";
import { scrollChange } from "./scrol.js";
import { eventValidation } from "./eventscript.js";
import { deleteEvent } from "./delete.js";
toggleMenu();
registerValidation();
scrollChange();
eventValidation();
deleteEvent();
